---
- hosts: webserver
  user: ansible
  connection: ssh
  become: yes
  vars:
    pkg1: httpd
    pkg2: docker
    pkg3: tomcat
    pkg4: mysql
    pkg5: java

  tasks: 

        - name: Install httpd server on host Machine
          action: yum pkg='{{pkg=1}}' state=present

        - name: Start httpd server on host Machine
          action: service name='{{pkg1}} state=started 

        - name: Stop httpd server on host Machine
          action: service name='{{pkg1}}' state=stopped

        - name: Intall docker on host Machine
          action: yum pkg='{{pkg2}}' state=present

        - name: Start docker on host Machine
          action: service name='{{pkg2}}' state=started

        - name: Stop docker on host Machine
          action: service name='{{pkg2}}' state=stopped

        - name: Install tomcat on host Machine
          action: yum pkg='{{pkg3}}' state=present

        - name: Install mysql on host Machine
          action: yum pkg='{{pkg4}}' state=present

        - name: Install java on host Machine
          action: yum pkg='{{pkg5}}' state=present

        
